## Basic edit on hosts file 

---
- name: Checking platform
  hosts: localhost
  gather_facts: false
  tasks:
 
## create dodge entry 

   - name: add dodge entry
     ansible.builtin.lineinfile:
      path: /etc/hosts
      line: 10.9.1.106 jhb-kiosk
      owner: root
      group: root
      mode: '0644'
     tags: 
      - setup
      - never

## Add some trouble shooting bits
   - name: troubleshooting connectivity 
     ignore_errors: yes
     block:

      - name: checking connectivity to dublin-kiosk
        shell: ping -c 1 -q 10.5.0.132
        register: dublin

      - name: checking connectivity to jhb-kiosk
        shell: ping -c 1 -q 10.5.0.172
        register: jhb

      - name: connectivity results to node 1 ipv4
        debug:
         msg: Pinging dublin {{ dublin }}

      - name: connectivity result to node 2 ipv4
        debug:
         msg: Pinging dublin {{ jhb }}

      - name: checking DNS resolution to dublin-kiosk
        shell: ping -c 1 -q dublin-kiosk
        register: dublin

      - name: checking DNS resolution to jhb-kiosk
        shell: ping -c 1 -q jhb-kiosk
        register: jhb

      - name: connectivity results to node 1
        debug:
         msg: Pinging dublin {{ dublin }}

      - name: connectivity result to node 2s
        debug:
         msg: Pinging dublin {{ jhb }}

      - name: recording failures or failed tasks
        set_fact: 
         dns_error: 1
         ip_error: 0
        when: "'FAILED' in command_result.stderr"
 
   - name: correct dns records
     ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^10\.9\.1\.106'
      line: ''
      owner: root
      group: root
      mode: '0644'
      
## Add Handler bits 
