## Basic edit on hosts file 

---
- name: Checking platform
  hosts: appnodes
  gather_facts: false
  remote_user: rhel
  become: true
#  become_method: su
#  become_user: root

  tasks:
 
## create dodge entry 

   - name: add dodge entry
     ansible.builtin.lineinfile:
      path: /etc/hosts
      line: 10.9.1.106 jhb-kiosk
      owner: root
      group: root
      mode: '0644'
     tags: 
      - setup
      - never

## Add some trouble shooting bits
   - name: troubleshooting connectivity 
    # ignore_errors: yes
     block:

      - name: checking connectivity to dublin-kiosk
        shell: ping -c 1 -q 10.5.0.132
        register: dublin

      - name: checking connectivity to jhb-kiosk
        shell: ping -c 1 -q 10.5.0.172
        register: jhb

      - name: connectivity results to node 1 ipv4
        debug:
         msg: PING IP DUBLIN NODE {{ dublin }}

      - name: connectivity result to node 2 ipv4
        debug:
         msg: PING IP JHB NODE {{ jhb }}

      - name: checking DNS resolution to dublin-kiosk
        shell: ping -c 1 -q dublin-kiosk
        register: dnsdublin

      - name: checking DNS resolution to jhb-kiosk
        shell: ping -c 1 -q jhb-kiosk
        register: dnsjhb

      - name: DNS results to node 1
        debug:
         msg: DUBLIN RESOLUTION {{ dnsdublin }}

      - name: DNS result to node 2s
        debug:
         msg: JHB RESOLUTION {{ dnsjhb }}

     rescue:

      - name: error on network
        block:
          - name: DNS error 
            debug: 
              msg: node connectivity not established

          - name: correct record dns drift 
            ansible.builtin.lineinfile:
             path: /etc/hosts
             regexp: '^10\.9\.1\.106'
             line: ''
             owner: root
             group: root
             mode: '0644'
   
          - name: network test
            shell: ping -c 1 -q dublin-kiosk && ping -c 1 -q jhb-kiosk
            register: ping

        notify: result

  handlers:

   - name: result
     debug:
      msg: connection successfull {{ ping }}
   



## Add Handler bits 
